/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rocketcredit.creditanalysis.api;

import com.rocketcredit.creditanalysis.model.CreditRequest;
import com.rocketcredit.creditanalysis.model.CreditResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-13T13:24:23.415761+02:00[Europe/Budapest]")
@Validated
@Tag(name = "creditscore", description = "the creditscore API")
public interface CreditscoreApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /creditscore : Analyze credit for a user’s purchase
     *
     * @param creditRequest  (required)
     * @return Credit decision (status code 200)
     */
    @Operation(
        operationId = "analyzeCredit",
        summary = "Analyze credit for a user’s purchase",
        responses = {
            @ApiResponse(responseCode = "200", description = "Credit decision", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreditResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/creditscore",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreditResponse> analyzeCredit(
        @Parameter(name = "CreditRequest", description = "", required = true) @Valid @RequestBody CreditRequest creditRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"score\" : 0, \"reason\" : \"reason\", \"approved\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
