# app/reasons.py
# Canonical, human-stable machine codes (don't change once shipped). The
# backend/React client maps them to plain-language text.

# Evidence
EVIDENCE_MISSING_PROFILE = "EVIDENCE_MISSING_PROFILE"
EVIDENCE_MISSING_HISTORY = "EVIDENCE_MISSING_HISTORY"
EVIDENCE_MISSING_FINANCE = "EVIDENCE_MISSING_FINANCE"

# Profile rules
PROFILE_ACCOUNT_NEW = "PROFILE_ACCOUNT_NEW"
PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
PROFILE_EMAIL_UNVERIFIED = "PROFILE_EMAIL_UNVERIFIED"

# Partner-history rules (kept from the legacy service)
PARTNER_TOO_FEW_ORDERS = "PARTNER_TOO_FEW_COMPLETED_ORDERS"
PARTNER_ON_TIME_LOW = "PARTNER_ON_TIME_LOW"
PARTNER_REFUND_RATE_HIGH = "PARTNER_REFUND_RATE_HIGH"
PARTNER_NO_HISTORY = "PARTNER_NO_HISTORY"

# Affordability
ZERO_CAPACITY = "ZERO_CAPACITY"
AMOUNT_ABOVE_POSSIBLE = "AMOUNT_ABOVE_POSSIBLE_AMOUNT"
AMOUNT_ABOVE_PARTNER_CAP = "AMOUNT_ABOVE_PARTNER_CAP"
AMOUNT_NEAR_LIMIT = "AMOUNT_NEAR_LIMIT"

# Combination
SCORE_LOW = "SCORE_LOW"
SCORE_INCONCLUSIVE = "SCORE_INCONCLUSIVE"
AI_FALLBACK_RULES_ONLY = "AI_FALLBACK_RULES_ONLY"
