/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rocketcredit.gateway.api;

import com.rocketcredit.gateway.api.CheckoutRequest;
import com.rocketcredit.gateway.api.CheckoutResponse;
import com.rocketcredit.gateway.api.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-20T16:30:25.909637+06:00[Asia/Bishkek]")
@Validated
@Tag(name = "checkout", description = "the checkout API")
public interface CheckoutApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /checkout : Run full checkout flow
     *
     * @param checkoutRequest  (required)
     * @return Approved &amp; scheduled (status code 200)
     *         or Credit denied / payment failed (status code 402)
     *         or Invalid input / email domain not allowed (status code 422)
     */
    @Operation(
        operationId = "checkoutPost",
        summary = "Run full checkout flow",
        responses = {
            @ApiResponse(responseCode = "200", description = "Approved & scheduled", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CheckoutResponse.class))
            }),
            @ApiResponse(responseCode = "402", description = "Credit denied / payment failed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "422", description = "Invalid input / email domain not allowed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/checkout",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CheckoutResponse> checkoutPost(
        @Parameter(name = "CheckoutRequest", description = "", required = true) @Valid @RequestBody CheckoutRequest checkoutRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"installmentDurationMonths\" : 6, \"reason\" : \"reason\", \"schedule\" : [ { \"amount\" : 1.4658129805029452, \"dueDate\" : \"2000-01-23\" }, { \"amount\" : 1.4658129805029452, \"dueDate\" : \"2000-01-23\" } ], \"approved\" : true, \"paymentId\" : \"paymentId\", \"repaymentPlanId\" : \"repaymentPlanId\", \"userId\" : 0, \"partnerPaymentId\" : \"partnerPaymentId\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
