/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rocketcredit.payment.api;

import com.rocketcredit.payment.model.CreateTransferRequest;
import com.rocketcredit.payment.model.ErrorResponse;
import com.rocketcredit.payment.model.Payment;
import com.rocketcredit.payment.model.PaymentPage;
import com.rocketcredit.payment.model.PaymentPatch;
import com.rocketcredit.payment.model.PaymentStatus;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-23T23:31:22.594277+06:00[Asia/Bishkek]")
@Validated
@Tag(name = "Transfers", description = "the Transfers API")
public interface PaymentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /payments/transfers : List transfers
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param status  (optional)
     * @param partnerPaymentId  (optional)
     * @param partnerId  (optional)
     * @param userId  (optional)
     * @return Page of transfers (status code 200)
     */
    @Operation(
        operationId = "paymentsTransfersGet",
        summary = "List transfers",
        tags = { "Transfers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Page of transfers", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PaymentPage.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/payments/transfers",
        produces = { "application/json" }
    )
    default ResponseEntity<PaymentPage> paymentsTransfersGet(
        @Min(0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(1) @Max(200) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) PaymentStatus status,
        @Parameter(name = "partnerPaymentId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "partnerPaymentId", required = false) String partnerPaymentId,
        @Parameter(name = "partnerId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "partnerId", required = false) String partnerId,
        @Parameter(name = "userId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = false) Integer userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total\" : 1, \"size\" : 6, \"page\" : 0, \"items\" : [ { \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /payments/transfers/{id}/cancel : Cancel a transfer (best-effort)
     *
     * @param id  (required)
     * @return Canceled (or already not active) (status code 200)
     *         or Cannot cancel (already TRANSFERRED) (status code 409)
     */
    @Operation(
        operationId = "paymentsTransfersIdCancelPost",
        summary = "Cancel a transfer (best-effort)",
        tags = { "Transfers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Canceled (or already not active)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Payment.class))
            }),
            @ApiResponse(responseCode = "409", description = "Cannot cancel (already TRANSFERRED)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/payments/transfers/{id}/cancel",
        produces = { "application/json" }
    )
    default ResponseEntity<Payment> paymentsTransfersIdCancelPost(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /payments/transfers/{id} : Get a transfer by internal id
     *
     * @param id  (required)
     * @return Found (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getPaymentsTransfersId",
        summary = "Get a transfer by internal id",
        tags = { "Transfers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Payment.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/payments/transfers/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Payment> getPaymentsTransfersId(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /payments/transfers/{id} : Update transfer status (internal/webhook/ops)
     *
     * @param id  (required)
     * @param paymentPatch  (required)
     * @return Updated (status code 200)
     *         or Invalid update (status code 400)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "patchPaymentsTransfersId",
        summary = "Update transfer status (internal/webhook/ops)",
        tags = { "Internal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Payment.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid update", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/payments/transfers/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Payment> patchPaymentsTransfersId(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "PaymentPatch", description = "", required = true) @Valid @RequestBody PaymentPatch paymentPatch
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /payments/transfers : Create &amp; execute a merchant transfer
     * Creates a payout to the partner’s payment address; idempotent via Idempotency-Key.
     *
     * @param createTransferRequest  (required)
     * @param idempotencyKey Prevents duplicate transfers for the same request. (optional)
     * @return Transfer created (status code 201)
     *         or Invalid request payload (status code 400)
     *         or Upstream PSP/bank failure (status code 502)
     */
    @Operation(
        operationId = "paymentsTransfersPost",
        summary = "Create & execute a merchant transfer",
        description = "Creates a payout to the partner’s payment address; idempotent via Idempotency-Key.",
        tags = { "Transfers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Transfer created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Payment.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request payload", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "502", description = "Upstream PSP/bank failure", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/payments/transfers",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Payment> paymentsTransfersPost(
        @Parameter(name = "CreateTransferRequest", description = "", required = true) @Valid @RequestBody CreateTransferRequest createTransferRequest,
        @Parameter(name = "Idempotency-Key", description = "Prevents duplicate transfers for the same request.", in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = false) String idempotencyKey
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"amount\" : 2.3021358869347655, \"item\" : { \"quantity\" : 7, \"price\" : 9.301444243932576, \"name\" : \"name\", \"sku\" : \"sku\" }, \"metadata\" : { \"key\" : \"\" }, \"userId\" : 5, \"providerPaymentId\" : \"providerPaymentId\", \"payee\" : { \"address\" : \"address\", \"name\" : \"name\", \"type\" : \"BANK_ACCOUNT\" }, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"provider\" : \"NONE\", \"failureReason\" : \"failureReason\", \"currency\" : \"currency\", \"id\" : 5, \"partnerId\" : \"partnerId\", \"partnerPaymentId\" : \"partnerPaymentId\", \"transferReference\" : \"transferReference\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
