services:

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - default

  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/credit-repayment || true
      "
    networks:
      - default

  gateway:
    build:
      context: ..
      dockerfile: rocket-credit-gateway/Dockerfile
    image: rocket-credit-gateway:latest
    ports:
      - "${GATEWAY_HOST_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_URL=redis://redis:6379
      - USER_DATA_URL=http://user-data:8080
      - CREDIT_ANALYSIS_URL=http://credit-analysis:8080
      - PAYMENT_URL=http://payment:8080
      - REPAYMENT_URL=http://repayment:8080
      - NOTIFICATION_URL=http://notification:8080

      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_REGION=us-east-1
      - S3_BUCKET=credit-repayment

      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      user-data:
        condition: service_healthy
      credit-analysis:
        condition: service_started
      payment:
        condition: service_started
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
      repayment:
        condition: service_started
      redis:
        condition: service_started

      # - notification

  user-data:
    build:
      context: ..
      dockerfile: rocket-credit-user-data/Dockerfile
    image: rocket-credit-user-data:latest
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/user-data?id=1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 30s

    depends_on:
      - userdb
      - minio
      - minio-init
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://userdb:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_REGION=us-east-1
      - S3_BUCKET=credit-repayment

  userdb:
    image: postgres:15
    container_name: userdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"

  credit-analysis:
    build:
      context: ..
      dockerfile: rocket-credit-analysis/Dockerfile
    image: rocket-credit-analysis:latest
    environment:
      - USER_DATA_URL=http://user-data:8080
      - SQLALCHEMY_URL=postgresql+psycopg://postgres:postgres@creditdb:5432/creditdb
      - APPROVE_THRESHOLD=0.60
      - PORT=8080 
      
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_REGION=us-east-1
      - S3_BUCKET=credit-repayment

      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/_health').read()"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 30s
    depends_on:
      - creditdb
      - minio
      - minio-init

  creditdb:
    image: postgres:15
    container_name: creditdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditdb
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d creditdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  payment:
    build:
      context: ../rocket-credit-payment
    image: rocket-credit-payment:latest
    env_file: .env
    depends_on:
      - paymentdb
      - minio
      - minio-init
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://paymentdb:5432/paymentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  paymentdb:
    image: postgres:15
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"

  repayment:
    build:
      context: ../rocket-credit-repayment
      dockerfile: Dockerfile
    image: rocket-credit-repayment:latest
    depends_on:
      - repaymentdb
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://repaymentdb:5432/repaymentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  repaymentdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repaymentdb
    ports:
      - "5436:5432"

  # notification:
  #   build:
  #     context: ../rocket-credit-notification
  #     dockerfile: Dockerfile
  #   image: rocket-credit-notification:latest
  #   depends_on:
  #     - notificationdb
  #   ports:
  #     - "8085:8080"   # host 8085 → container 8080
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://notificationdb:5432/notificationdb
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres

  # notificationdb:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: notificationdb
  #   ports:
  #     - "5437:5432"

networks:
  default:
    name: rocket-credit-network

volumes:
  redisdata:
