"""Source catalog for the private diploma demo. Prices and titles are illustrative."""

# fixture_id, name, USD price, category, description, Commons search phrase
PRODUCTS = [
    # Netflix: five existing fixture IDs, then 25 illustrative titles and bundles.
    ("streambox-basic-monthly", "Basic monthly plan", "9.99", "Plans", "A one-month streaming plan for a single screen in the demo catalog.", "television remote control"),
    ("streambox-standard-monthly", "Standard monthly plan", "15.99", "Plans", "A one-month plan for two screens with an expanded viewing selection.", "watching television living room"),
    ("streambox-4k-monthly", "4K + HDR monthly plan", "24.99", "Plans", "An illustrative high-resolution monthly viewing plan.", "4k television screen"),
    ("streambox-premium-annual", "Premium annual plan", "159.99", "Plans", "Twelve months of premium access shown as one demo purchase.", "home cinema projector"),
    ("streambox-family-annual", "Family annual plan", "199.99", "Plans", "An annual multi-screen plan for a household in this demo.", "family watching television"),
    ("streambox-northern-lights", "Northern Lights", "7.99", "Films", "A fictional travel film following a photographer across winter skies.", "aurora borealis night sky"),
    ("streambox-last-train", "The Last Train Home", "6.99", "Films", "A fictional quiet drama about an unexpected trip back to a hometown.", "train station evening"),
    ("streambox-deep-blue", "Deep Blue Current", "8.99", "Films", "A fictional ocean adventure about a team mapping a hidden reef.", "underwater coral reef"),
    ("streambox-city-after-rain", "City After Rain", "6.99", "Films", "A fictional urban mystery set across one stormy evening.", "city street rain night"),
    ("streambox-red-desert", "Red Desert Road", "7.99", "Films", "A fictional road story through wide desert landscapes.", "desert road landscape"),
    ("streambox-glass-garden", "The Glass Garden", "6.99", "Films", "A fictional family story centered on a remarkable greenhouse.", "greenhouse plants glass"),
    ("streambox-orbit", "Orbit 17", "8.99", "Films", "A fictional science-fiction rescue mission above Earth.", "earth from space astronaut"),
    ("streambox-harbor", "Harbor at Dawn", "6.99", "Films", "A fictional coastal drama about a returning sailor.", "harbor sunrise boats"),
    ("streambox-forest", "Forest Signal", "7.99", "Films", "A fictional adventure following a radio signal into the woods.", "forest trail sunlight"),
    ("streambox-mountain", "Beyond the Summit", "8.99", "Films", "A fictional climbing documentary about teamwork in the mountains.", "mountain climbing hikers"),
    ("streambox-night-shift", "Night Shift", "12.99", "Series", "A fictional workplace series following an overnight hospital team.", "hospital hallway night"),
    ("streambox-corner-cafe", "The Corner Café", "11.99", "Series", "A fictional character series centered on a neighborhood café.", "cafe interior coffee"),
    ("streambox-hidden-islands", "Hidden Islands", "13.99", "Series", "A fictional nature series visiting remote island habitats.", "tropical island aerial"),
    ("streambox-makers", "Makers & Machines", "12.99", "Series", "A fictional documentary series about modern workshops.", "workshop tools maker"),
    ("streambox-capital-files", "Capital Files", "13.99", "Series", "A fictional investigative series set in a busy capital city.", "city skyline dusk"),
    ("streambox-river-house", "River House", "11.99", "Series", "A fictional family series set beside a winding river.", "river house landscape"),
    ("streambox-after-school", "After School Club", "10.99", "Series", "A fictional coming-of-age series about a student project team.", "students school classroom"),
    ("streambox-open-kitchen", "Open Kitchen", "11.99", "Series", "A fictional food series exploring home cooks and recipes.", "cooking kitchen food"),
    ("streambox-timekeepers", "The Timekeepers", "13.99", "Series", "A fictional mystery series built around an old clock workshop.", "vintage clock workshop"),
    ("streambox-wild-coast", "Wild Coast", "12.99", "Series", "A fictional nature series about coastal wildlife.", "sea coast wildlife"),
    ("streambox-documentary-bundle", "Documentary bundle", "39.99", "Bundles", "An illustrative bundle of science, history, and nature viewing.", "documentary camera nature"),
    ("streambox-film-night-bundle", "Film night bundle", "29.99", "Bundles", "An illustrative collection of four film-night selections.", "movie theater seats"),
    ("streambox-family-weekend", "Family weekend bundle", "24.99", "Bundles", "A fictional weekend viewing collection for a family.", "family movie night"),
    ("streambox-series-season", "Series season bundle", "49.99", "Bundles", "An illustrative full-season access package for one series.", "television series screen"),
    ("streambox-cinema-year", "Cinema year bundle", "129.99", "Bundles", "An illustrative annual collection of rotating films.", "cinema film projector"),

    # Amazon: five existing fixture IDs, then 25 electronics/home entries.
    ("markethub-earbuds", "Wireless earbuds", "129.00", "Audio", "Compact in-ear audio with a portable charging case.", "wireless earbuds case"),
    ("markethub-monitor-27", "27-inch QHD monitor", "279.00", "Workspace", "A large QHD display for a home desk setup.", "computer monitor desk"),
    ("markethub-robot-vacuum", "Robot vacuum", "349.00", "Home", "An automated floor cleaner for everyday household use.", "robot vacuum cleaner"),
    ("markethub-espresso", "Espresso machine", "499.00", "Kitchen", "A countertop machine for espresso and milk drinks.", "espresso machine kitchen"),
    ("markethub-standing-desk", "Standing desk", "599.00", "Workspace", "An adjustable desk that supports seated and standing work.", "standing desk office"),
    ("markethub-bluetooth-speaker", "Bluetooth speaker", "89.00", "Audio", "A portable speaker for music around the home.", "portable bluetooth speaker"),
    ("markethub-headphones", "Over-ear headphones", "179.00", "Audio", "Comfortable headphones for focused listening.", "over ear headphones"),
    ("markethub-soundbar", "Compact soundbar", "249.00", "Audio", "A slim speaker unit for improving television sound.", "television soundbar"),
    ("markethub-turntable", "Record turntable", "219.00", "Audio", "A simple turntable for playing vinyl records.", "vinyl record turntable"),
    ("markethub-keyboard", "Mechanical keyboard", "119.00", "Workspace", "A tactile keyboard for a productive desktop setup.", "mechanical keyboard"),
    ("markethub-mouse", "Wireless mouse", "49.00", "Workspace", "A cordless pointing device for laptop and desktop work.", "wireless computer mouse"),
    ("markethub-webcam", "HD webcam", "79.00", "Workspace", "A desktop camera for clear video calls.", "webcam computer"),
    ("markethub-desk-lamp", "LED desk lamp", "69.00", "Workspace", "An adjustable task light for reading and working.", "led desk lamp"),
    ("markethub-office-chair", "Ergonomic office chair", "429.00", "Workspace", "A supportive chair for a home office.", "ergonomic office chair"),
    ("markethub-tablet", "10-inch tablet", "399.00", "Tech", "A portable screen for reading, browsing, and media.", "tablet computer device"),
    ("markethub-ereader", "E-reader", "139.00", "Tech", "A lightweight digital reader with a paper-like screen.", "e reader device"),
    ("markethub-camera", "Mirrorless camera", "899.00", "Tech", "A compact interchangeable-lens camera for photography.", "mirrorless digital camera"),
    ("markethub-tripod", "Travel tripod", "89.00", "Tech", "A folding support for stable camera shots.", "camera tripod"),
    ("markethub-projector", "Home projector", "749.00", "Tech", "A portable projector for large-screen viewing.", "home projector"),
    ("markethub-air-purifier", "Air purifier", "299.00", "Home", "A compact unit for filtering indoor air.", "home air purifier"),
    ("markethub-coffee-grinder", "Coffee grinder", "119.00", "Kitchen", "An electric grinder for fresh coffee beans.", "coffee grinder"),
    ("markethub-air-fryer", "Air fryer", "159.00", "Kitchen", "A countertop cooker for crisp meals with circulating air.", "air fryer kitchen"),
    ("markethub-blender", "Countertop blender", "99.00", "Kitchen", "A blender for smoothies, sauces, and soups.", "kitchen blender"),
    ("markethub-kettle", "Electric kettle", "59.00", "Kitchen", "A quick-boil kettle for tea and hot drinks.", "electric kettle"),
    ("markethub-floor-lamp", "Floor lamp", "129.00", "Home", "A freestanding light for a living room corner.", "floor lamp living room"),
    ("markethub-bookshelf", "Modular bookshelf", "249.00", "Home", "A flexible shelf for books and home storage.", "bookshelf furniture"),
    ("markethub-plant-stand", "Plant stand", "69.00", "Home", "A raised display for indoor plants.", "indoor plant stand"),
    ("markethub-luggage", "Carry-on suitcase", "189.00", "Travel", "A compact wheeled case for short trips.", "carry on suitcase"),
    ("markethub-backpack", "Travel backpack", "119.00", "Travel", "A durable daypack with room for daily essentials.", "travel backpack"),
    ("markethub-bike-helmet", "Cycling helmet", "79.00", "Travel", "A lightweight protective helmet for cycling.", "bicycle helmet"),

    # Zara: five existing fixture IDs, then 25 apparel entries.
    ("threadly-linen-shirt", "Linen shirt", "59.00", "Tops", "A breathable linen shirt for warm days.", "linen shirt clothing"),
    ("threadly-denim-jacket", "Denim jacket", "99.00", "Outerwear", "A versatile denim layer for changing seasons.", "denim jacket fashion"),
    ("threadly-running-shoes", "Running shoes", "129.00", "Shoes", "Lightweight trainers for everyday movement.", "running shoes sneakers"),
    ("threadly-wool-coat", "Wool coat", "189.00", "Outerwear", "A structured coat for colder weather.", "wool coat fashion"),
    ("threadly-leather-boots", "Leather boots", "219.00", "Shoes", "Sturdy ankle boots for daily wear.", "leather boots footwear"),
    ("threadly-cotton-tee", "Cotton T-shirt", "25.00", "Tops", "A soft everyday tee with a relaxed fit.", "cotton t shirt clothing"),
    ("threadly-striped-shirt", "Striped poplin shirt", "55.00", "Tops", "A crisp striped shirt for casual or office wear.", "striped shirt fashion"),
    ("threadly-knit-cardigan", "Knit cardigan", "79.00", "Knitwear", "A warm button-front layer for cooler days.", "knit cardigan sweater"),
    ("threadly-cashmere-sweater", "Cashmere-blend sweater", "149.00", "Knitwear", "A soft knit designed for easy layering.", "cashmere sweater"),
    ("threadly-turtleneck", "Ribbed turtleneck", "49.00", "Knitwear", "A close-fitting knit for layering under jackets.", "turtleneck sweater"),
    ("threadly-jeans", "Straight-leg jeans", "69.00", "Bottoms", "Classic denim jeans with a straight silhouette.", "blue jeans clothing"),
    ("threadly-trousers", "Tailored trousers", "89.00", "Bottoms", "Clean-cut trousers for smart everyday outfits.", "tailored trousers fashion"),
    ("threadly-cargo-pants", "Cargo pants", "75.00", "Bottoms", "Utility-inspired trousers with practical pockets.", "cargo pants clothing"),
    ("threadly-midi-skirt", "Pleated midi skirt", "69.00", "Bottoms", "A flowing skirt with soft pleats.", "pleated midi skirt"),
    ("threadly-summer-dress", "Cotton summer dress", "89.00", "Dresses", "An easy cotton dress for warm weather.", "summer dress fashion"),
    ("threadly-evening-dress", "Evening dress", "169.00", "Dresses", "A refined long dress for evening occasions.", "evening dress fashion"),
    ("threadly-shirt-dress", "Shirt dress", "99.00", "Dresses", "A collared dress with a relaxed fit.", "shirt dress fashion"),
    ("threadly-blazer", "Single-breasted blazer", "149.00", "Outerwear", "A tailored layer for work and weekend outfits.", "single breasted blazer"),
    ("threadly-trench", "Lightweight trench coat", "179.00", "Outerwear", "A practical long coat for mild rainy days.", "trench coat clothing"),
    ("threadly-puffer", "Quilted puffer jacket", "159.00", "Outerwear", "A padded jacket for cold-weather layering.", "puffer jacket clothing"),
    ("threadly-sneakers", "Canvas sneakers", "69.00", "Shoes", "Simple low-top shoes for casual outfits.", "canvas sneakers shoes"),
    ("threadly-loafers", "Classic loafers", "99.00", "Shoes", "Slip-on shoes with a polished everyday look.", "leather loafers shoes"),
    ("threadly-sandals", "Leather sandals", "79.00", "Shoes", "Open-toe sandals for sunny days.", "leather sandals fashion"),
    ("threadly-tote", "Canvas tote bag", "39.00", "Accessories", "A roomy reusable bag for daily essentials.", "canvas tote bag"),
    ("threadly-crossbody", "Crossbody bag", "89.00", "Accessories", "A compact hands-free bag with an adjustable strap.", "crossbody bag fashion"),
    ("threadly-scarf", "Woven scarf", "35.00", "Accessories", "A light woven scarf for layering.", "woven scarf fashion"),
    ("threadly-belt", "Leather belt", "45.00", "Accessories", "A simple belt to finish casual and formal looks.", "leather belt clothing"),
    ("threadly-sunglasses", "Square sunglasses", "59.00", "Accessories", "Angular sunglasses for bright days.", "square sunglasses fashion"),
    ("threadly-beanie", "Ribbed beanie", "29.00", "Accessories", "A soft knit hat for cold weather.", "knit beanie hat"),
    ("threadly-weekender", "Weekender bag", "119.00", "Accessories", "A soft travel bag for short trips.", "weekender travel bag"),
]


if __name__ == "__main__":
    from collections import Counter
    counts = Counter(item[0].split("-", 1)[0] for item in PRODUCTS)
    assert counts == {"streambox": 30, "markethub": 30, "threadly": 30}, counts
    assert len({item[0] for item in PRODUCTS}) == len(PRODUCTS)
    print(counts)
