ALTER TABLE users 
ADD COLUMN annual_income DOUBLE PRECISION DEFAULT 50000.0,
ADD COLUMN credit_bureau_score INTEGER DEFAULT 650,
ADD COLUMN social_consent BOOLEAN DEFAULT FALSE,
ADD COLUMN social_handles JSONB;